apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.deployment.image }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        envFrom:
          - configMapRef:
              name: {{ .Values.name }}-configmap
          - secretRef:
              name: {{ .Values.name }}-secrets
        resources:
          requests:
            cpu: {{ .Values.deployment.resourcesrequestscpu }}
            memory: {{ .Values.deployment.resourcesrequestsmemory }}
          limits:
            cpu: {{ .Values.deployment.resourceslimitscpu }}
            memory: {{ .Values.deployment.resourceslimitmemory }}