apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_PASSWORD: {{ .Values.secrets.databasePassword }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword }}