apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name-ingress }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name-service }}
            port:
              number: {{ .Values.port }}
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name-service }}
            port:
              number: {{ .Values.port }}