apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_PASSWORD: {{ .Values.databasePassword }}
  REDIS_PASSWORD: {{ .Values.redisPassword }}