apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.ingress.apiIngressHost }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name }}-service
            port:
              number: {{ .Values.ingress.apiIngressServicePort }}
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name }}-service
            port:
              number: {{ .Values.ingress.apiIngressServicePort }}