apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: cloudns
spec:
  replicas: {{.values.deployment.replicas}}
  selector:
    matchLabels:
      app: {{.values.selectormatchlabelsapp}}
  template:
    metadata:
      labels:
        app: {{.values.templatelabelsapp}}
    spec:
      containers:
      - name: {{.values.containername}}
        image: {{.values.containerimage}}
        imagePullPolicy: {{.values.imagePullPolicy}}
        ports:
        - containerPort: {{.values.containerPort}}