apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: cloudns
spec:
  selector:
    app: {{ .Values.service.specSelectorapp}}
  ports:
  - protocol: {{ .Values.service.portsProtocol}}
    port: {{ .Values.service.portsPort}}
    targetPort: {{ .Values.service.portTargetPort}}
  type: ClusterIP