apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: cloudns
spec:
  replicas: {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      app: {{.Values.deployment.selectormatchlabelsapp}}
  template:
    metadata:
      labels:
        app: {{.Values.deployment.templatelabelsapp}}
    spec:
      containers:
      - name: {{.Values.deployment.containername}}
        image: {{.Values.deployment.containerimage}}
        imagePullPolicy: {{.Values.deployment.imagePullPolicy}}
        ports:
        - containerPort: {{.Values.deployment.containerPort}}